[package]
name = "pinned-init"
version = "0.0.1"
edition = "2021"

authors = ["y86-dev"]
license = "MIT OR Apache-2.0"
description = "Library to facilitate safe pinned initialization"
readme = "README.md"

documentation = "https://docs.rs/pinned-init"
repository = "https://github.com/y86-dev/pinned-init"
keywords = ["safe", "pin", "init", "no-std", "rust-patterns"]
categories = ["no-std", "rust-patterns", "embedded"]

[dependencies]

[features]
default = ["std"]
std = []
alloc = []
never_type = []

[[example]]
name = "linked_list"
required-features = ["never_type"]

[[example]]
name = "mutex"
required-features = ["never_type"]

[dev-dependencies]
libc = "0.2"
