[package]
name = "pinned-init-macro"
version = "0.0.2"
edition = "2021"

authors = ["y86-dev"]
license = "MIT OR Apache-2.0"
description = "Proc macros for the pinned-init crate."

repository = "https://github.com/Rust-for-Linux/pinned-init"

[lib]
proc-macro = true

[dependencies]
