permissions:
  contents: read
on:
  push:
    branches: [kernel]
  schedule:
    - cron: '7 7 * * *'
name: kernel
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: kernel
          path: pin-init
      - run: git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      - run: |
          cp -r linux/rust/pin-init .
          cd pin-init
          git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]
