permissions:
  contents: read
on:
  push:
    branches: [main, kernel]
  pull_request:
  schedule:
    - cron: '7 7 * * *'
name: rolling
jobs:
  nightly:
    runs-on: ubuntu-latest
    name: ubuntu / nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: cargo install cargo-expand
      - run: cargo test --locked
  update:
    runs-on: ubuntu-latest
    name: ubuntu / nightly / updated
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: cargo install cargo-expand
      - run: cargo update
      - run: cargo test --locked
        env:
          RUSTFLAGS: -D deprecated
