permissions:
  contents: read
on:
  push:
    branches: [kernel, next]
  schedule:
    - cron: '7 7 * * *'
  workflow_dispatch:

name: sync-check
jobs:
  torvalds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: kernel
          path: pin-init
      - run: git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      - run: |
          cp -r linux/rust/pin-init .
          cd pin-init
          if ! git diff --quiet ; then
              git diff
              false
          fi
          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
              git status
              false
          fi
  pin-init-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: next
          path: pin-init
      - uses: actions/checkout@v4
        with:
          repository: "Rust-for-Linux/linux"
          ref: pin-init-next
          path: linux
      - run: |
          cp -r linux/rust/pin-init .
          cd pin-init
          if ! git diff --quiet ; then
              git diff
              false
          fi
          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
              git status
              false
          fi
