permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: test
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      # https://twitter.com/jonhoo/status/1571290371124260865
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets
      # https://github.com/rust-lang/cargo/issues/6669
      - name: cargo test --doc
        run: cargo test --locked --all-features --doc
  os-check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / nightly
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test
        run: cargo test --locked --all-features --all-targets
# for now disable coverage
# coverage:
#   runs-on: ubuntu-latest
#   name: ubuntu / nightly / coverage
#   steps:
#     - uses: actions/checkout@v3
#       with:
#         submodules: true
#     - name: Install nightly
#       uses: dtolnay/rust-toolchain@nightly
#       with:
#         components: llvm-tools-preview,rust-src
#     - name: cargo install cargo-llvm-cov
#       uses: taiki-e/install-action@cargo-llvm-cov
#     - name: cargo generate-lockfile
#       if: hashFiles('Cargo.lock') == ''
#       run: cargo generate-lockfile
#     - name: cargo llvm-cov
#       run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info
#     - name: Upload to codecov.io
#       uses: codecov/codecov-action@v3
#       with:
#         fail_ci_if_error: true
